import type { Metadata } from "next";
import { Geist, Geist_Mono, Cormorant_Garamond } from "next/font/google";
import { ThemeProvider } from "./providers";
import GlobalHeader from "./components/GlobalHeader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} ${cormorantGaramond.variable} antialiased min-h-screen flex flex-col bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-200 selection:bg-yellow-600/30 selection:text-white`}>
        <ThemeProvider>
          <GlobalHeader />
        <main className="flex-1 flex flex-col w-full max-w-7xl mx-auto p-6 md:p-8">
          {children}
        </main>
        <footer id="contacto" className="py-8 text-center text-sm text-zinc-500 border-t border-zinc-200 dark:border-zinc-800">
          <p>© {new Date().getFullYear()} Barbershop SaaS. All rights reserved.</p>
        </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
